# Generated by Django 6.0.3 on 2026-04-17 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='menu.dishes')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]